version: '3.4'

services:
  frontend:
    image: frontend
    command: ng serve --host 0.0.0.0
    ports:
      - 4200:4200
    environment:
      - HOST=backend
    links:
      - backend
  backend:
    image: backend
    environment:
      - MONGO_URL=mongo
    command: yarn start
    ports: 
      - 3000:3000
    links:
      - mongo
  mongo:
    image: mongo
    ports: 
      - 27017:27018