version: '3.1'

services:
  backend:
    image: backend
    environment:
      - MONGO_URL=mongo
    command: yarn start
    ports: 
      - 3000:3000
    links:
      - mongo
  mongo:
    image: mongo
    ports: 
      - 27017:27017